### ISSUE TITLE
Live ISO environment suspends even when on AC power, killing cnchi installer.

### ISSUE THREAD

**Issue by timlepes** [Antergos/antergos-iso#112] opened 2018-07-06 23:47 UTC
The live ISO is set up to suspend to RAM after 20 minutes even when on AC power.  This of course kills your installation if you have a slow connection.  Change the default so it doesn't suspend automatically when on AC power.  There are lots of reasons why one may want to "walk away" and let the thing alone while it downloads and installs.  Very unhelpful to find it suspended to RAM.  And extremely irritating when it won't continue downloading and installing after you wake it back up.  Then, of course, you can't just kill cnchi and start over without rebooting.  Cnchi doesn't like to start over without making me reboot (and wait).  No joy was had today...

**Comment by timlepes** [comment] 2018-07-15 22:41
I do realize it is possible to turn off the suspend-to-disk when on A/C setting before running the installer.  I put the bug in because I think it would be friendlier to other users if the default were changed.  Thanks.

**Comment by karasu** [comment] 2018-07-23 08:17
Duplicate of https://github.com/Antergos/antergos-iso/issues/109

**Closed by karasu** 2018-07-23 08:17 UTC
Labels: duplicate
