### ISSUE TITLE
UEFI Installation minor bug

### ISSUE THREAD

**Issue by tydlwav** [Antergos/antergos-iso#60] opened 2016-06-01 02:57 UTC
With a UEFI installation, the option of "antergos USB" does not work and would return a "can not start /arch/boot/vmlinuz" error. The workaround is to choose the "antergos CD/DVD" option. Though this is not a huge problem, it would scare many antergos (and arch) new-comers away. The lack of documentation (wiki page dedicated to this problem) also made figuring this out a minor hassle for me.

**Comment by Mikaela** [comment] 2016-06-01 04:50
Potential duplicate of https://github.com/Antergos/antergos-iso/issues/52 ?

**Comment by LibreMichael** [comment] 2016-06-02 02:06
Nope. It doesn't matter if the drive is ntfs or fat32 or ext4. It's a problem of the 'uefi usb install' option not loading the kernel. See [this](https://forum.antergos.com/topic/4081/how-to-dual-boot-antergos-windows-uefi-expanded) for reference. The issue should be quite easy to resolve. I think it may be a few lines of careless code contributing to the mess. I haven't had the time to look at the source code yet. I'd fork it if I found a problem in the code.

**Closed** 2016-06-17 04:01 UTC
